AWSTemplateFormatVersion: "2010-09-09"
Description: Create a role to assume and create a resource we'll have access to
Parameters:
    BucketName:
        Type: String
        Default: "deestsv1"
Resources:
    S3Bucket:
        Type: "AWS::S3::Bucket"
        DeletionPolicy: Retain
        Properties:
            BucketName: ${BucketName}
    StsRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          AWS: "arn:aws:iam::992382693593:user/Davidsts"
                          # Service:
                          #       - s3.amazonaws.com
                      Action:
                          - "sts:AssumeRole"
            Path: /
            Policies:
                - PolicyName: s3access
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action: "*"
                            Resource:
                                [
                                    "arn:aws:s3:::*",
                                    "arn:aws:s3:::${BucketName}",
                                    "arn:aws:s3:::${BucketName}/*",
                                ]
